### ISSUE TITLE
在包启用后，list_fd命令导致死机

### ISSUE THREAD

**Issue by ghost** [mysterywolf/rt_kprintf_threadsafe#1]
主要提两个存在的问题：

1. 在启用该软件包后，**shell 中调用 list_fd 命令会直接导致系统死机**，无论在板子还是模拟器上都能够百分百复现
2. 该包会修改 console device 的open_flag但是却没有做保护，在多核环境下可能会在存在冲突。在调试某款芯片的smp时出现了冲突而导致shell无法正常工作的情况

**Comment by mysterywolf** [comment]
我都没有注意到你提issue了，你关闭issue我才注意到。。。关闭issue是因为问题解决了？

**Comment by wdfk-prog** [comment]
- 又看了一下代码运行流程
- list_fd首先先rt_enter_critical();，将rt_scheduler_lock_nest + 1；
- rt_kprintf中启用了互斥量，rt_mutex_take函数首先进行RT_DEBUG_SCHEDULER_AVAILABLE
- RT_DEBUG_SCHEDULER_AVAILABLE中运行
```c
if (rt_critical_level() != 0)                                         \
        {                                                                     \
            rt_kprintf("Function[%s]: scheduler is not available\n",          \
                    __FUNCTION__);                                            \
            RT_ASSERT(0)                                                      \
        }     
```
- rt_critical_level判断到当前值不为0，又打印rt_kprintf。导致死循环

**Comment by mysterywolf** [comment]
嗯而且这个软件包确实没有考虑到多核的情况

**Comment by wdfk-prog** [comment]
> 嗯而且这个软件包确实没有考虑到多核的情况

或许应该在rt_mutex_take之前执行一次rt_critical_level() ，判断不为零直接退出返回负数？

**Comment by mysterywolf** [comment]
https://github.com/RT-Thread/rt-thread/pull/6606
感谢提交PR 该问题已经在此处得到解决。
